# Generated by Django 2.2.1 on 2019-09-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estufa1_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.CharField(max_length=200)),
                ('temperatura', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'estufa1',
            },
        ),
    ]
